Repository itb-community/ITB-ModLoader, pull requests merged in 2022-08, with the labels that each got.

#155 Globalize exclusiveElements in spawner_backend
  scripts/mod_loader/hard-alter.lua
Labels: enhancement

#149 Add pilot deck selector to choose which pilots appear in time pods
  scripts/mod_loader/altered/drops.lua
  scripts/mod_loader/bootstrap/constants.lua
  scripts/mod_loader/bootstrap/utils.lua
  scripts/mod_loader/localization/dictionary_English.lua
  scripts/mod_loader/mod_loader.lua
  scripts/mod_loader/modapi/drops.lua
  scripts/mod_loader/modui/__scripts.lua
  scripts/mod_loader/modui/_deck_selector.lua
  scripts/mod_loader/modui/modcontent_entries.lua
  scripts/mod_loader/modui/pilot_arrange.lua
  scripts/mod_loader/modui/pilot_deck_selector.lua
  scripts/mod_loader/modui/weapon_deck_selector.lua
Labels: enhancement

#154 Alternative method to rework how skill effect metadata is stored to fix #140
  scripts/mod_loader/modapi/skills.lua
Labels: bug

#158 Add Default_Move and fix Rosie abilities not being called on custom pawn move skills
  scripts/mod_loader/altered/skills.lua
Labels: bug, enhancement

#152 Sort squad units when adding squad
  scripts/mod_loader/modapi/squad.lua
Labels: bug
