Repository itb-community/ITB-ModLoader, pull requests merged in 2023-02, with the labels that each got.

#190 Add FTL pilots to deck selector
  scripts/mod_loader/bootstrap/constants.lua
  scripts/mod_loader/localization/dictionary_English.lua
  scripts/mod_loader/modapi/drops.lua
  scripts/mod_loader/modui/pilot_deck_selector.lua
Labels: enhancement

#191 Fix SetNeutral so it works without memEdit
  scripts/mod_loader/modapi/pawn.lua
Labels: bug

#193 Take advantage of the new injection point provided by Subset
  scripts/modloader.lua
  scripts/modloader.lua.bak
  scripts/scripts.lua
  scripts/scripts.lua.bak
  uninstall_modloader.bat
Labels: cleanup
